### ISSUE TITLE
Work incorrectly in my phone

### ISSUE THREAD

**Issue by XYScience** [SubhrajyotiSen/GlideGallery#1]
Look at my phone，nexus5 Android7.1：http://171.15.197.81/xdispatch/7xthed.com1.z0.glb.clouddn.com/GlideGallery-error.mp4

**Comment by SubhrajyotiSen** [comment]
Hey!
Are you referring to the exit animation?

**Comment by XYScience** [comment]
The enter and exit animation all work incorrectly。You can look at the video：http://171.15.197.81/xdispatch/7xthed.com1.z0.glb.clouddn.com/GlideGallery-error.mp4

**Comment by SubhrajyotiSen** [comment]
Thanks a lot for filing the issue!
This commit should fix your issue  63057bbff5b2800f64cea7eb05a6a6e7e599ed1e
