### ISSUE TITLE
How to replace static IMGS url list in Utils with a Json object from a network location

### ISSUE THREAD

**Issue by wtnh** [SubhrajyotiSen/GlideGallery#3]
HI - this is very nice code, but I would like to pull down a Url list of images from a network location using Volley. This would replace the hard-coded string array you have in the example in the Utils class.
Since this is a more practical application, would you consider adding this functionality to your example? I have not figured out (yet) how to add this. One issue I see is that the getData method in Utils is called from other Gallery classes, and wrapping getData in a Volley method might interfere. It would also be nice to use a JSON object for this instead of a String[], but this seems like a minor detail.

**Comment by SubhrajyotiSen** [comment]
Hi.
If you want to fetch the list of image URLs from a network location, it is a good idea to use JSON. Because most API responses will give resultd in JSON format. 
You will need to rewrite the getData method as follows:

1. Make your network call using Volley (or Retrofit). You will mostly get a JSON reponse
2. Create an empty String array
3. Parse the JSON reponse and add the URLs to the String array
4. Return the array. 

This way other parts of the code won't require any changes.

**Comment by wtnh** [comment]
Thanks for your help. Is your suggestion to re-write getData to include the Volley method? I was hesitant to do that since it gets called from your other code and I did not know how to avoid "breaking" your code.

What I had thought of doing was the following:
1) an onClick listener in a RecyclerView invokes a request to a separate Volley class, passing the URL of a JSON object which contains a string of URLs pointing to images (same format as you use)
2) using a callback, the Volley method passes back the JSON object to the onClick
3) the onClick passes the JSON to the Utils class, which has a new method to parse the JSON and populate the array and then call the main Gallery activity.

In some stub testing, I ran into some issues parsing and populating IMGS[] correctly, but I can overcome that. I suppose I could get more sophisticated and use listeners for the Volley response, but right now I am struggling a bit with the basics. What do you think of this approach?

**Comment by SubhrajyotiSen** [comment]
I don't think you need a click listener for that. You can directly replace the body of getData() to return the array of URLs as string array after you have parsed from JSON response

**Comment by wtnh** [comment]
I should have explained that my app has an onClick listener for the user to select a particular set of galleries from a list in a RecyclerView. Depending on which button is clicked a different URL pointer is supplied to the Volley request. So I am dealing with multiple galleries which are defined by multiple URL lists.

**Comment by SubhrajyotiSen** [comment]
In that case, your approach works
